export const ACTIVITY_TYPES = {
  LEAD_CREATED: 'lead_created',
  LEAD_UPDATED: 'lead_updated',
  LEAD_DELETED: 'lead_deleted',
  LEAD_ASSIGNED: 'lead_assigned',
  LEAD_STATUS_CHANGED: 'lead_status_changed',
  AI_MESSAGE_GENERATED: 'ai_message_generated',
  AI_TEMPLATE_USED: 'ai_template_used',
  EMAIL_SCHEDULED: 'email_scheduled',
  EMAIL_SENT: 'email_sent',
  EMAIL_FAILED: 'email_failed',
  EMAIL_CANCELLED: 'email_cancelled',
  NOTE_ADDED: 'note_added',
  NOTE_UPDATED: 'note_updated',
  NOTE_DELETED: 'note_deleted',
  FOLLOW_UP_SCHEDULED: 'follow_up_scheduled',
  EMAIL_RECEIVED: 'email_received',
};

export const ACTIVITY_LABELS = {
  [ACTIVITY_TYPES.LEAD_CREATED]: 'Lead Created',
  [ACTIVITY_TYPES.LEAD_UPDATED]: 'Lead Updated',
  [ACTIVITY_TYPES.LEAD_DELETED]: 'Lead Deleted',
  [ACTIVITY_TYPES.LEAD_ASSIGNED]: 'Lead Assigned',
  [ACTIVITY_TYPES.LEAD_STATUS_CHANGED]: 'Status Changed',
  [ACTIVITY_TYPES.AI_MESSAGE_GENERATED]: 'AI Message Generated',
  [ACTIVITY_TYPES.AI_TEMPLATE_USED]: 'AI Template Used',
  [ACTIVITY_TYPES.EMAIL_SCHEDULED]: 'Email Scheduled',
  [ACTIVITY_TYPES.EMAIL_SENT]: 'Email Sent',
  [ACTIVITY_TYPES.EMAIL_FAILED]: 'Email Failed',
  [ACTIVITY_TYPES.EMAIL_CANCELLED]: 'Email Cancelled',
  [ACTIVITY_TYPES.NOTE_ADDED]: 'Note Added',
  [ACTIVITY_TYPES.NOTE_UPDATED]: 'Note Updated',
  [ACTIVITY_TYPES.NOTE_DELETED]: 'Note Deleted',
  [ACTIVITY_TYPES.FOLLOW_UP_SCHEDULED]: 'Follow-Up Scheduled',
  [ACTIVITY_TYPES.EMAIL_RECEIVED]: 'Reply Received',
};
